add Read-me
wandergithub/tribute-page pull request #1
Opened 2022-03-22 16:54 UTC by Gedewon

# update the readmefile

2022-03-22 16:55 UTC, Gedewon commented on README.md
> +acknowledgment: project from tem member, Wander Gonzalez.
Make professional acknowledgment by following the industry standard

2022-03-22 16:59 UTC, Gedewon reviewed
Require changes :)

2022-03-22 16:59 UTC, Gedewon commented on index.html
>      " id="tribute-link" target="_blank">More Info about Micheal Jackson of the blessed memory</a>
Use more descriptive tags and use the correct Semantic tages

2022-03-22 17:17 UTC, phelian23 commented on README.md
> +acknowledgment: project from tem member, Wander Gonzalez.
- [ ] Nice one calling the developer's attention to the fact that they should've written a professional acknowledgment 👍. However, it is good to be polite while giving a review as it will make the developer feel appreciated for their effort and they won't regard changes as negative feedback. Kindly edit the comment to sound polite, you can include "please or kindly"

2022-03-22 17:20 UTC, phelian23 commented on index.html
>      " id="tribute-link" target="_blank">More Info about Micheal Jackson of the blessed memory</a>
- [ ] Nice effort pointing out the use of semantic tags. However, it is good to be polite as much as possible, and also backup your suggestions with reasons why you think they should do so. Please, let us edit this comment to be polite and give a reason to as well. It makes the developer feel appreciated for their effort and they won't regard changes as negative feedback.

2022-03-22 17:22 UTC, phelian23 requested changes
Hi @Gedewon, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 17:24 UTC, Gedewon commented on index.html
>      " id="tribute-link" target="_blank">More Info about Micheal Jackson of the blessed memory</a>
@phelian23 Oo thank you for the review,I will make sure to give polite comment.

2022-03-22 17:32 UTC, Gedewon commented on index.html
>      " id="tribute-link" target="_blank">More Info about Micheal Jackson of the blessed memory</a>
@phelian23 Thank you for your comment.do you have any suggestion ?

2022-03-23 16:09 UTC, OLIPLICHE approved these changes
Hi, @Gedewon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-27 19:41 UTC, closed without merging